### ISSUE TITLE
Accessing the window/document to hydrate initial markup.

### ISSUE THREAD

**Issue by chrstntdd** [stefanjudis/react-in-a-worker#1]
I've found a couple examples around that are doing something similar to what you're doing here and I tried to follow the same steps. I have created my own Cloudflare Worker with the following script:

```js
// index.js
import React from 'react'
import ReactDOMServer from 'react-dom/server'

class HelloMessage extends React.Component {
  render() {
    return <div>Hello, {this.props.name} 👋</div>
  }
}

const htmlHeader = `<!DOCTYPE html><html><head lang="en">
<meta charset="utf-8" />
<link rel="icon" href="data:,">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
</head><body><div id="root">`

const htmlFooter = `</div>
<script src="./worker.js"></script>
</body></html>
`

function handleRequest(event) {
  const app = ReactDOMServer.renderToString(<HelloMessage name="World" />)

  return new Response(htmlHeader + app + htmlFooter, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
    },
  })
}

self.addEventListener('fetch', event => {
  event.respondWith(handleRequest(event))
})

if (typeof window !== 'undefined') {
  console.log('this is never hit')
}
```

and a `webpack.config.js` identical to the one you have in this project. The initial HTML is returned as I expect, but that is all.

I don't know if this is a problem with locally developing or what, but where I would normally `render` or `hydrate`, after getting the target DOM node, I am never able to reach that block where I would be able to access the DOM. Is there something I'm missing here?

Cheers!

**Comment by stefanjudis** [comment]
Do you have the URL where this is deployed? It could maybe be that your client `worker.js` is not properly loaded? After a quick look that looks okay'ish. :)

**Comment by chrstntdd** [comment]
Unfortunately I'm not even able to deploy it either - I keep getting back 400 errors when I try to publish. I pushed up what I have so far - after removing the `account_id` from the `wrangler.toml`.  I can successfully get it running in development with `NODE_ENV=development wrangler preview --watch` only.

[the repo](https://github.com/chrstntdd/uni_worker)

**Comment by stefanjudis** [comment]
Okay... I think I figured the problem. :) 

https://2839bfab47d4b920c5e52eb7057376e0.cloudflareworkers.com/worker.js

Responds with HTML. That's not gonna work. If I remember correctly I had the assets on netlify. And only the `/` routes were served from a worker, the rest was proxied through.

E.g. this is my netlify site https://react-in-a-worker.netlify.com/ and this is cloudflare sitting in fron of it https://www.react-in-a-worker.rocks/. :)  Hope that helps. :)

**Comment by chrstntdd** [comment]
Ah! That makes sense and is what I probably should be doing.
I hacked around and created a separate webpack build to handle building a browser only bundle using a separate entry point that calls `ReactDOM.render`to kick things off. Additionally, I have a step in my publishing script to write the emitted JS assets to KV and in the worker I read from KV to inline the JS into the HTML I generate by the worker itself. I have it [published here](https://uni_worker.chrstntdd.workers.dev/) but now I'm dealing with some `urql` troubles to refetch the data after submitting a new query.

Thank you for your help!

**Comment by stefanjudis** [comment]
Looks like you resolved it. :) Good luck on the further journey. :)
